### ISSUE TITLE
Eventhub failing with AMQP error in Azure Activity Logs Source

### ISSUE THREAD

**Issue by sanjay-motorq** [triggermesh/triggermesh#1002]
I have an issue when trying to use azure activity logs source.
(I'm using the latest TriggerMesh version with Knative version 1.50)

I'm getting the following error.

`{"severity":"ERROR","timestamp":"2022-06-29T09:50:22.150585538Z","logger":"azureeventhubsource","caller":"trace/trace.go:104","message":"*Error{Condition: amqp:unauthorized-access, Description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://knative-testing.servicebus.windows.net/insights-activity-logs/consumergroups/$default/partitions/0'. TrackingId:<>, SystemTracker:gateway5, Timestamp:2022-06-29T09:50:21, Info: map[]}","commit":"130294b","stacktrace":"github.com/triggermesh/triggermesh/pkg/sources/adapter/azureeventhubsource/trace.(*zapLogger).Error\n\tgithub.com/triggermesh/triggermesh/pkg/sources/adapter/azureeventhubsource/trace/trace.go:104\ngithub.com/Azure/azure-event-hubs-go/v3.(*receiver).newSessionAndLink\n\tgithub.com/Azure/azure-event-hubs-go/v3@v3.3.18/receiver.go:413\ngithub.com/Azure/azure-event-hubs-go/v3.(*Hub).newReceiver\n\tgithub.com/Azure/azure-event-hubs-go/v3@v3.3.18/receiver.go:169\ngithub.com/Azure/azure-event-hubs-go/v3.(*Hub).Receive\n\tgithub.com/Azure/azure-event-hubs-go/v3@v3.3.18/hub.go:621\ngithub.com/triggermesh/triggermesh/pkg/sources/adapter/azureeventhubsource.(*adapter).Start\n\tgithub.com/triggermesh/triggermesh/pkg/sources/adapter/azureeventhubsource/adapter.go:182\nknative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\tknative.dev/eventing@v0.31.1-0.20220523181303-c3e13967001f/pkg/adapter/v2/main.go:257\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\tknative.dev/eventing@v0.31.1-0.20220523181303-c3e13967001f/pkg/adapter/v2/main.go:157\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\tknative.dev/eventing@v0.31.1-0.20220523181303-c3e13967001f/pkg/adapter/v2/main.go:132\nknative.dev/eventing/pkg/adapter/v2.Main\n\tknative.dev/eventing@v0.31.1-0.20220523181303-c3e13967001f/pkg/adapter/v2/main.go:128\nmain.main\n\tgithub.com/triggermesh/triggermesh/cmd/azureeventhubsource-adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}`

`amqp:unauthorized-access` and `Listen' claim(s) are required to perform this operation` caught my eye, but I wasn't able to fix the issue.

I have created a service principle and assigned all the permissions it needs ( source )

An eventhub insights-activity-logs is created which receives events, but there are no outgoing messages.

This is the source yaml file that I used

```
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureActivityLogsSource
metadata:
  name: activitylogsource
  namespace: kn-testing
spec:
  subscriptionID: <>

  categories:
  - Administrative
  - Security
  - Policy

  destination:
    eventHubs:
      namespaceID: <>

  auth:
    servicePrincipal:
      tenantID:
        value: <>
      clientID:
        value: <>
      clientSecret:
        value: <>
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brok
      namespace: kn-testing
```
