### ISSUE TITLE
Sink ref and uri cannot be used together

### ISSUE THREAD

**Issue by Kaiass** [triggermesh/triggermesh#1193]
Knative sinks have ref and uri properties which allow making combined uri like in example below:
```
  sink:
    ref:
      apiVersion: v1
      kind: Service
      namespace: default
      name: mysink
    uri: /extra/path
```

Some TriggerMesh sources don't allow that. For example AWSSQSSource has "oneOf" set in spec:
```
  oneOf:
  - required: [ref]
  - required: [uri]
```
[AWSSQSSource yaml](https://github.com/triggermesh/triggermesh/blob/main/config/300-awssqssource.yaml)

Setting it to "anyOf" helps and works fine.
Is it done by intention or is it a mistake?
