### ISSUE TITLE
GoogleCloudPubSubSource sink does not allow both ref and uri

### ISSUE THREAD

**Issue by rnewton** [triggermesh/triggermesh#1218]
I tried searching for this issue, but didn't find anything. Please close if it's a duplicate. 

I'm trying to set up a `GoogleCloudPubSubSource` to accept events from PubSub and forward them to a service within my cluster that doesn't have any public endpoints. I've set up the config as 

```yml
kind: GoogleCloudPubSubSource
apiVersion: sources.triggermesh.io/v1alpha1
metadata:
  name: source-name
  namespace: my-namespace
spec:
  topic: projects/my-project/topics/my-topic
  serviceAccountKey:
    valueFromSecret:
      name: sa
      key: keyfile
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: my-service
    uri: "/relative/url"
```

This is suggested to work by the [docs here](https://pkg.go.dev/knative.dev/pkg/apis/duck/v1#Destination), but the actual json schema does not allow this:

```
"sink": {
          "description": "The destination of events received via change notifications.",
          "oneOf": [
            {
              "required": [
                "ref"
              ]
            },
            {
              "required": [
                "uri"
              ]
            }
          ],
...
```

Results in error:

```
The GoogleCloudPubSubSource "source-name" is invalid: <nil>: Invalid value: "": "spec.sink" must validate one and only one schema (oneOf). Found 2 valid alternatives
```

Are the docs wrong or the schema?
