### ISSUE TITLE
Support for assume role

### ISSUE THREAD

**Issue by mhoshi-vm** [triggermesh/triggermesh#1253]
We have an org that does not allow iam user access.
We are allowed to access objects via the "assume role"
https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/

While the following maybe a solution, it is not good enough, as this is only for EKS instances and not for instances outside of EKS.
https://github.com/triggermesh/triggermesh/pull/1243

**Comment by sebgoa** [comment]
Hi, could you tell us:

1. Which target you are using and maybe describe a bit the use case ?
2. Describe how you run Kubernetes outside EKS ?

thank you

**Comment by mhoshi-vm** [comment]
Hi,
Our current aws account, does not allow directly creating IAM users, instead we are required to link users from another aws account, using "assume roles".
Very similar to the following.
https://tomgregory.com/jenkins-assume-role-in-another-aws-account/#1_Why_would_Jenkins_need_to_assume_a_role_in_AWS
This requires
- for Authentication both credentials and IAM role as the input
- with those credentials the client is required to generate a temporary credential to programmatically access 
I believe if this is possible, we can remove the "only for EKS" limitation

**Comment by odacremolbap** [comment]
Thanks @mhoshi-vm , we will triage the issue and get back here.

**Comment by tzununbekov** [comment]
Better Late than Never 🙂
I'm working on this issue and already have a fix that enables cross-account IAM. The question is what would be a better Spec for auth object in AWS components? There are two options:

1. Re-using existing `IamRole`:
```yaml
  auth:
    credentials:
      accessKeyID:
        value: <key id>
      secretAccessKey:
        value: <secret key>
    iamRole: <IAM role ARN>
```
-if both `credentials` and `iamRole` are provided, the access key is used to create the client session, and `iamRole` represents the assumed role resource. 

2. New attribute:
```yaml
  auth:
    credentials:
      accessKeyID:
        value: <key id>
      secretAccessKey:
        value: <secret key>
      assumeIamRole: <IAM role ARN>
```
-new attribute, say `assumeIamRole `, explicitly enables cross-account IAM impersonation.


What would be the opinions on that matter? Personally, I wanted to re-use the existing attribute, but now that I have 2nd option written down, I'm second-guessing myself.
/cc @mhoshi-vm @odacremolbap
