### ISSUE TITLE
KafkaSource with RedPanda issue

### ISSUE THREAD

**Issue by jmcx** [triggermesh/triggermesh#1255]
Using tmctl to connect KafkaSource to RedPanda. Getting an error in the KafkaSource logs: `kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc`

**Environment**
* RedPanda running on my MacOS M1 using rpk (RedPanda CLI), some commands I used for the config and other examples:
    * rpk topic create new-file --brokers 127.0.0.1:CHANGEME
    * rpk cluster config set superusers "['admin', 'console']"
    * rpk acl user create console -p xf9kqEVHJPYQT
    * rpk acl user create registry -p fwlLypJ+6bZom
    * rpk acl user create admin -p sbJjhSrzgoMbG
    * rpk cluster config set enable_sasl true
    * rpk topic create new-file --user admin --password sbJjhSrzgoMbG --sasl-mechanism SCRAM-SHA-256
* tmctl v1.22
    * tmctl create source kafka --bootstrapServers 127.0.0.1:9092 --topics new-file --groupID mygroup --auth.username admin --auth.password.value sbJjhSrzgoMbG  --auth.saslEnable true --auth.tlsEnable false --auth.securityMechanism SCRAM-SHA-256

KafkaSource env:

```yaml
"Env": [
                "K_LOGGING_CONFIG={\"zap-logger-config\":\"{\\\"level\\\": \\\"error\\\"}\"}",
                "BOOTSTRAP_SERVERS=127.0.0.1:9092",
                "TOPIC=new-file",
                "SASL_ENABLE=true",
                "GROUP_ID=mygroup",
                "TLS_ENABLE=false",
                "SECURITY_MECHANISMS=SCRAM-SHA-256",
                "USERNAME=admin",
                "PASSWORD=sbJjhSrzgoMbG",
                "K_SINK=http://host.docker.internal:54261",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/ko-app",
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
                "KO_DATA_PATH=/var/run/ko"
            ],
```

Docker compose file for installing redpanda and redpanda console: 

```yaml
version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v22.3.8
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    volumes:
      - ./volumes/certs:/certs:ro
      - ./volumes/redpanda-etc:/etc/redpanda
      - ./volumes/redpanda-var:/var/lib/redpanda/data

  console:
    image: docker.redpanda.com/vectorized/console:v2.1.1
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
            username: console
            password: xf9kqEVHJPYQT
          sasl:
            enabled: true
            username: console
            password: xf9kqEVHJPYQT
            mechanism: SCRAM-SHA-256
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda
```

Maybe useful related issue? https://github.com/Shopify/sarama/pull/2086
