### ISSUE TITLE
KafkaTarget cannot connect to Upstash Kafka

### ISSUE THREAD

**Issue by phucnt1992** [triggermesh/triggermesh#1260]
Hi team,

I am using TriggerMesh with KafkaTarget. Unluckily, Upstash Kafka requires custom properties as below:

```
properties:
        sasl.mechanism: SCRAM-SHA-512
        security. Protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="<username>" password="<password>";
```

Reference:
https://docs.upstash.com/kafka/howto/monitor-with-kafkaui

I reviewed the TriggerMesh code and realized there was a technical limit to use ScramLoginModule.

Is there any workaround solution to integrate Upstash Kafka, especially KafkTarget?

Look forward to getting your advice.

**Comment by odacremolbap** [comment]
Thanks for the issue @phucnt1992 

Unfortunately the recent release contained an [issue regarding some kafka credentials management](https://github.com/triggermesh/triggermesh/pull/1259).
Those should be fixed at the next patch release (coming very soon), but you can try our dev build (it is being built as I write this, will edit this comment and post here the container image tag).

This is the manifest that should make those credentials work:

```yaml
apiVersion: targets.triggermesh.io/v1alpha1
kind: KafkaTarget
metadata:
  name: sample
spec:
  bootstrapServers:
  - quiet-akita-13329-eu1-kafka.upstash.io:9092
  topic: mytopic
  auth:
    saslEnable: true
    tlsEnable: true
    securityMechanism: SCRAM-SHA-256
    username:
      valueFromSecret:
        name: upstashcreds
        key: user
    password:
      valueFromSecret:
        name: upstashcreds
        key: password
```
