### ISSUE TITLE
Defining consumer group on the Azure Event Hub source

### ISSUE THREAD

**Issue by NatanMish** [triggermesh/triggermesh#1344]
Hi all,

Not sure if I got something wrong or if it's just missing, but I want to define an Azure Event Hub source and direct it to use a specific consumer group and I can't find where that is defined in the CRD: https://github.com/triggermesh/triggermesh/blob/c86f3c47d57acc294e73fe6cb1c200914f742fe2/config/300-azureeventhubssource.yaml

I specifically need the Azure Event Hub and can't use Kafka.

Thanks!

**Comment by tzununbekov** [comment]
Hey @NatanMish. I looked up the client code and it seems that we use the default consumer group in the source adapter and currently there is no way to overwrite it. Let me check what would it take to expose the consumer group parameter in the CRD and I get back to you with the update.

**Comment by tzununbekov** [comment]
@NatanMish we updated our latest release, Custom Group support should be there. Please let us know if it works for you.

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureEventHubsSource
metadata:
  name: sample
spec:
  eventHubID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyGroup/providers/Microsoft.EventHub/namespaces/MyNamespace/eventhubs/MyEvents
  consumerGroup: consumer-group-name
  ...
```

**Comment by NatanMish** [comment]
Thank you very much all! I'll test it out and let you guys know

**Comment by NatanMish** [comment]
Ok I've encountered another issue. Here is what I have so far - I am trying to redirect messages from one eventhub to another:

1. Event hub source defined as:
```
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureEventHubsSource
metadata:
  name: sample
spec:
  eventHubID: /subscriptions/b9f079fb-0edc-4636-8216-91374b91b736/resourceGroups/mg-testeenv/providers/Microsoft.EventHub/namespaces/testehinstance/eventhubs/test-triggermesh

  auth:
    servicePrincipal:
      tenantID:
        valueFromSecret:
          name: azure
          key: tenantID
      clientID:
        valueFromSecret:
          name: azure
          key: clientID
      clientSecret:
        valueFromSecret:
          name: azure
          key: clientSecret

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: knative-broker
```

2. Knative Broker defined as:
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: knative-broker
  namespace: default
```

3. Trigger defined as:
```
apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  name: mdemo
spec:
  broker:
    kind: Broker
    group: eventing.knative.dev/v1
    name: knative-broker
  target:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: AzureEventHubsTarget
      name: sample-target

  delivery:
    retry: 3
    deadLetterSink:
      ref:
        kind: Service
        apiVersion: v1
        name: display-deadlettersink
```

4. Eventhub target:
```
apiVersion: targets.triggermesh.io/v1alpha1
kind: AzureEventHubsTarget
metadata:
  name: sample-target
spec:
  eventHubID: /subscriptions/b9f079fb-0edc-4636-8216-91374b91b736/resourceGroups/mg-testeenv/providers/Microsoft.EventHub/namespaces/testehinstance/eventhubs/triggermesh-target

  auth:
    sasToken:
      connectionString:
        valueFromSecret:
          name: azure
          key: connectionString
```

After applying all of these I get this message in the eventhub source events feed: 
```
Warning  Unhealthy  6s (x10 over 34s)  kubelet            Startup probe failed: HTTP probe failed with statuscode: 503                                                               
Warning  Unhealthy  5s (x3 over 31s)   kubelet            Startup probe failed: Get "http://10.244.0.45:8080/health": dial tcp 10.244.0.45:8080: connect: connection refused
```

Any help would be appreciated!

**Comment by sebgoa** [comment]
Any chance you can join Slack so that we can help you debug this: https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA


From your manifest it looks like you are using a Triggermesh Trigger object with a Knative Broker and that won't work.

You can either switch to a triggermesh broker (if you have installed it) or switch to a knative Trigger.

So either

```
apiVersion: eventing.triggermesh.io/v1alpha1
kind: MemoryBroker
metadata:
  name: demo
```

Or:

```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mdemo
spec:
  broker: knative-broker
  subscriber:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: AzureEventHubsTarget
      name: sample-target
```

I would start by trying a knative Trigger
