### ISSUE TITLE
Support deleting CloudEvents extension attributes with the JSON Transformation

### ISSUE THREAD

**Issue by jmcx** [triggermesh/triggermesh#1386]
When using the Google Cloud Storage source, I'm getting lots of unwanted extension attributes in events:

```
☁️  cloudevents.Event
Context Attributes,
  specversion: 1.0
  type: com.google.cloud.storage.notification
  source: gs://jmcx-test
  id: 7283369936877024
  time: 2023-04-04T08:36:13.699Z
  datacontenttype: application/json
Extensions,
  pubsubmsgbucketid: jmcx-test
  pubsubmsgeventtime: 2023-04-04T08:36:13.658837Z
  pubsubmsgeventtype: OBJECT_FINALIZE
  pubsubmsgnotificationconfig: projects/_/buckets/jmcx-test/notificationConfigs/1
  pubsubmsgobjectgeneration: 1680597373646330
  pubsubmsgobjectid: MonaLisa.jpeg
  pubsubmsgoverwrotegeneration: 1680597265096910
  pubsubmsgpayloadformat: JSON_API_V1
Data,
  {
    "Data": {
      "kind": "storage#object",
...
```

I'm trying to remove them with a JSON transformation like so, but to no avail:

```
context:
- operation: add
  paths:
  - key: type
    value: io.triggermesh.objectStorage.objectCreated
  - key: source
    value: googlecloudstorage:$bucketName
  - key: subject
    value: $objectName
- operation: delete
  paths:
  - key: extensions.pubsubmsgbucketid
  - key: extensions.pubsubmsgeventtime
  - key: extensions.pubsubmsgeventtype
  - key: extensions.pubsubmsgnotificationconfig
  - key: extensions.pubsubmsgobjectgeneration
  - key: extensions.pubsubmsgobjectid
  - key: extensions.pubsubmsgpayloadformat
 ...
```

**Comment by jmcx** [comment]
Also tried these syntaxes which didn't work either (failing silently, the rest of the transformation works):

```
- operation: delete
  paths:
  - key: Extensions.pubsubmsgbucketid
  - key: Extensions.pubsubmsgeventtime
```

```
- operation: delete
  paths:
  - key: Extensions.*
```

```
context:
- operation: add
  paths:
  - key: type
    value: io.triggermesh.objectStorage.objectCreated
  - key: source
    value: googlecloudstorage:$bucketName
  - key: subject
    value: $objectName
- operation: delete
  paths:
  - key: Extensions
```
