### ISSUE TITLE
Unable to use iam role for authentication with awss3source

### ISSUE THREAD

**Issue by jewel-mascarenhas** [triggermesh/triggermesh#1396]
I had earlier used the aws access key and secret for the AWSS3Source to authenticate which worked very well for me, however when I try to use the IAM role for authentication it gives me the following error:

**AWSS3Source in version "v1alpha1" cannot be handled as a AWSS3Source: strict decoding error: unknown field "spec.auth.iamrole"** 

```
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: s3data
spec:
  arn: arn:aws:s3:::xxxxx

  eventTypes:
  - s3:ObjectCreated:*
  - s3:ObjectRemoved:*

  auth:
    iamrole: arn:aws:iam::xxxxxxx:role/new-eks-service-role

  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: myredis

```
Can anyone please suggest how can I overcome this ?

**Comment by sebgoa** [comment]
Hi @jewel-mascarenhas we will reply shortly. in the meantime you can join us on Slack at https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA where we can help in a more real-time fashion

**Comment by FranBarrera** [comment]
Hey @jewel-mascarenhas the CRD's elements are casing sensitive, so for the iam role, should be `iamRole`, you can check it [here](https://github.com/triggermesh/triggermesh/blob/617c8a2d15c812e422140a29b5ceb4c2169a7afc/config/300-awss3source.yaml#L189) Let us know if you find any other issues.

**Comment by jewel-mascarenhas** [comment]
Hello @FranBarrera thank you for the help, yes it did solve the above issue, however the AWSS3Source still fails to come up with the error NOClient, resulting in no pod/deployment coming up.

**The AWSS3Source yaml is as follows:**

```
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: s3data-new-1

spec:
  arn: arn:aws:s3:::eks-triggermesh

  eventTypes:
  - s3:ObjectCreated:*
  - s3:ObjectRemoved:*

  auth:
    iamRole: arn:aws:iam::xxxxxx:role/new-eks-service-role

  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: myredis
```
The role is has all the permission required as stated in the documentation.  

In order to test connectivity of a pod to aws services (s3 bucket) , I used a service account called eks-tm and bound it to the same role used above and that works well for me.
The manifest for the pod is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: eks-tm
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
Can you please advise if I have missed any configuration for the AWSS3Source deployment ?
