### ISSUE TITLE
Functions CRD reference docs are missing `ceOverrides`

### ISSUE THREAD

**Issue by jmcx** [triggermesh/triggermesh#1442]
`ceOverrides` lets you do things like hard code a CE type for event returned by a function in its response:

```yaml
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: order-event-classifier
spec:
  runtime: python
  adapterOverrides:
    public: true
   ceOverrides:
    extensions:
      type: my.overridden.type
  entrypoint: endpoint
  code: |
    from random import randrange
    def endpoint(event, context):
...
```

This isn't visible in the [CRD reference docs](https://docs.triggermesh.io/1.25/reference/extensions/#extensions.triggermesh.io/v1alpha1.FunctionSpec):

<img width="707" alt="image" src="https://github.com/triggermesh/triggermesh/assets/5730842/8c29904d-ab68-44b4-b0e4-5dd787a79ec9">

I've create this issue in this repo because AFAIU this is something that would come from the CRD OAS specs. 

I'm working on a docs PR in parallel, I'm interested to know exactly what else can be done with these `ceOverrides`. 

Also, I wonder why the parameter is called `extensions` => shouldn't it be more like `context`. Is there a way to add CE extensions via `ceOverrides`?
