### ISSUE TITLE
Azure EventHubs not working as a source with Azure Auth (oauth client creds flow)

### ISSUE THREAD

**Issue by drdamour** [triggermesh/triggermesh#1467]
i have a service principal setup with Azure Event Hubs Data Receiver  IAM role and created a broker and added my eh as a source, but nothing shows in watch or if i setup a console.  There are events on the hub.  trie dwith and without --consumerGroup

same creds work for sending events as target, but no events coming in as source.  docs don't really have a troubleshooting section log last line is 

{"severity":"INFO","timestamp":"2023-07-07T23:04:17.549059319Z","logger":"azureeventhubssource","caller":"azureeventhubssource/adapter.go:224","message":"Starting Event Hub message receivers for partitions [0 1 2 3 4 5 6 7]","commit":"1360cec"}

which looks right but nothing coming thru...

```
 tmctl describe
Broker     Status
jde-na     online(http://localhost:40085)

Trigger                     Target      Filter
jde-na-trigger-1ecc048e     console     type is *""

Source        Kind                     EventTypes                               Status
jde-na-eh     azureeventhubssource     com.microsoft.azure.eventhub.message     online(http://localhost:46111)

Target      Kind                                                        Expected Events     Status
console     service (gcr.io/triggermesh/triggermesh-console:v0.0.1)     *                   online(http://localhost:44633)
```

**Comment by jmcx** [comment]
Hi @drdamour 👋 

Thanks for reaching out and for the issues you raised. It looks like you've got some great recommendations for improving the overall experience of tmctl on windows, plus some other issues. 

For this kind of troubleshooting specifically (Event Hubs), is there any chance you're able to join our community Slack so that we can help you there? You'll get responses from the engineers and it is a much more interactive way to debug these kinds of issues.

Also, would you have 30 minutes or so to discuss your use case and to help us prioritise your various issues and requests? That would be fantastic! 

We really appreciate the time you've put in so far and hope to get you up and running quickly.

**Comment by tzununbekov** [comment]
@drdamour could you share the output of this command - `tmctl dump --no-secrets`? Thanks.

**Comment by jmcx** [comment]
Hi @drdamour, were you able to provide @tzununbekov with the details he requested? Or perhaps we can close this one?

**Comment by drdamour** [comment]
no haven't been able to yet, should be able to try it again tomorrow

**Comment by drdamour** [comment]
```
---
apiVersion: eventing.triggermesh.io/v1alpha1
kind: RedisBroker
metadata:
  labels:
    triggermesh.io/context: jde-na
  name: jde-na
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    triggermesh.io/context: jde-na
    triggermesh.io/role: target
  name: console
spec:
  template:
    spec:
      containers:
      - env: []
        image: gcr.io/triggermesh/triggermesh-console:v0.0.1
        name: user-container
---
apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  labels:
    triggermesh.io/context: jde-na
  name: jde-na-trigger-1ecc048e
spec:
  broker:
    group: eventing.triggermesh.io
    kind: RedisBroker
    name: jde-na
  filters:
  - suffix:
      type: ""
  target:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: console
---
apiVersion: v1
data:
  clientID: <user_input>
  clientSecret: <user_input>
  tenantID: <user_input>
kind: Secret
metadata:
  labels:
    triggermesh.io/context: jde-na
  name: jde-na-eh-secret
type: Opaque
---
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureEventHubsSource
metadata:
  labels:
    triggermesh.io/context: jde-na
  name: jde-na-eh
spec:
  auth:
    servicePrincipal:
      clientID:
        valueFromSecret:
          key: clientID
          name: jde-na-eh-secret
      clientSecret:
        valueFromSecret:
          key: clientSecret
          name: jde-na-eh-secret
      tenantID:
        valueFromSecret:
          key: tenantID
          name: jde-na-eh-secret
  consumerGroup: ""
  eventHubID: /subscriptions/<omitted>/resourceGroups/<omitted>/providers/Microsoft.EventHub/namespaces/<omitted>/eventhubs/products
  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: jde-na
```

one thing that stands out to me is the dempt consumerGroup because i used 

```
tmctl create source azureeventhubs <bunch omitted> --consumerGroup "$Default"
```

to create the source
