### ISSUE TITLE
Trigger and trigger policy issue in Triggermesh

### ISSUE THREAD

**Issue by akshaypandhare17** [triggermesh/triggermesh#1540]
Hi all, 

I am not sure whether this is a right channel or not to post a issue regarding triggermesh. We are trying to integrate  triggermesh with our existing systems and we are following triggermesh official documentation for creating Source, Broker, Trigger and Target. We are able to create all the resources except for the Trigger resource. 

Our source is google pub sub and target is a endpoint of Cloud run service and we are looking for transforming the request using transformations available in Triggermesh.

I am using below manifest file for creating Trigger resource.

```
apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  name: http-trigger
spec:
  broker:
    group: eventing.triggermesh.io/v1alpha1
    kind: MemoryBroker
    name: pubsub-broker
  target:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: HTTPTarget
      name: triggermesh-http
```

I am creating trigger resource using `kubectl apply -f trigger.yaml` command where trigger.yaml file contains above yaml data.

But trigger resource is not getting created in the k8s cluster.

```
akshaypandhare@AKSHAY-PANDHARE triggermesh % kubectl apply -f trigger.yaml 
trigger.eventing.triggermesh.io/http-trigger created
akshaypandhare@AKSHAY-PANDHARE triggermesh % 
akshaypandhare@AKSHAY-PANDHARE triggermesh % kubectl get trigger -A
No resources found
akshaypandhare@AKSHAY-PANDHARE triggermesh % 
```

Even though kubectl apply command is creating trigger resource I am not able to see it in kubectl get command. I confuse whether it is a configuration issue or issue with any CRD in triggermesh.

We really appreciate any help on this as we are stuck on this from past couple of days.
