### ISSUE TITLE
Function should not send a response when returned Null

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/triggermesh#238]
Function should return no event/no payload when the Null value for the language is returned.

Right now this code is producing a new event as a reply:
```yaml
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: ocimetrics-to-logz
spec:
  runtime: python
  responseIsEvent: true
  public: false
  ceOverrides:
    extensions:
      source: ocimetrics-to-logz
  entrypoint: handleOCImetrics
  code: |
    def handleOCImetrics(event, context):
      return None
```

Function should be able to
- If `Null` is returned ACK should be sent back with default attributes.
- If an event is returned but the `data` element contains the `Null` value, and ACK should be sent back with user attributes.
- If an event is returned with `data` in it (not `Null` but some content or the 0 value), return ACK plus the payload, just as it does now.
