### ISSUE TITLE
Switch from Event Hubs to Service Bus as event destination for Azure events

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#268]
### Context

Two of our Azure sources rely on Event Grid to subscribe to events: the _Blob Storage source_ and the _Event Grid source_ itself.

These two currently use **Event Hubs** as event destination (Event Grid _endpoint_), and our Event Hubs adapter picks up from there.

### Proposal

I suggest we switch the default event destination to **Service Bus**.
At the end of the day this should be considered an implementation detail, so why?

 - Service Bus is both cheaper and easier to integrate with. It provides familiar queuing and pub/sub primitives where a message is delivered once to subscribers, then forgotten.

- Event Hubs, on the other end, is similar to Kafka. It is focused on message streaming and data is persisted by default. Clients are expected to deal with partitions, offsets, etc.

I believe Service Bus is simply a better fit for sourcing events into TriggerMesh. Once such event has been consumed and injected into the platform, it is unlikely that someone cares about persisting it into Azure. And if they do, it should be done with intention, so we could maybe offer the choice to keep Event Hubs as an option.

### Possible API change

Current API, for reference: [samples/sources/azureeventgridsource.yaml](https://github.com/triggermesh/triggermesh/blob/e79d151b57c6931083ed9d45c6bcc8095b2b18f4/config/samples/sources/azureeventgridsource.yaml#L32-L34)

In order to make it clear what the endpoint-related settings are, we could introduce a new `endpoint` sub-level to the spec:

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureEventGridSource

# ...

spec:

  # ...

  endpoint:  # Optional. Default to 'serviceBus' with managed queue.

    # Only *one* possible choice per AzureEventGridSource instance:

    serviceBus:
      namespaceID: /subscriptions/[...]/resourceGroups/MyGroup/providers/Microsoft.ServiceBus/namespaces/MyNamespace
      queueName: MyQueue  # Optional. Managed by the source if not provided.

    eventHubs:
      namespaceID: /subscriptions/[...]/resourceGroups/MyGroup/providers/Microsoft.EventHub/namespaces/MyNamespace
      eventHubName: MyHub  # Optional. Managed by the source if not provided.
```

### External links

Pricing
- [Event Hubs](https://azure.microsoft.com/en-us/pricing/details/event-hubs/)
- [Service Bus](https://azure.microsoft.com/en-us/pricing/details/service-bus/)
