### ISSUE TITLE
Clean up release YAMLs before publishing them

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#280]
`ko` tends to replace manifests which didn't pass a filter (label selector) with _null_ documents:

```yaml
apiVersion: myapi/v0
Kind: Example

---
       # <-- this is a null document, e.g. where a CRD used to be
---

---

---

apiVersion: myapi/v0
Kind: Example

---

# ...
```

It also keeps all license headers while concatenating manifests:

```yaml
# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: myapi/v0
Kind: Example

---

# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: myapi/v0
Kind: Example

---

# ...
```

Both of them are harmless, but since we treat this output as release artifacts, we could as well keep them readable by cleaning up these unnecessary parts:

```yaml
# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");

apiVersion: myapi/v0
Kind: Example

---

apiVersion: myapi/v0
Kind: Example

---

# ...
