### ISSUE TITLE
Allow fan-out over SNS topic

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#32]
### Problem

Currently, there is no possibility for _multiple_ subscribers to create a notification configuration in the _same_ bucket. AWS rejects the request with the error `Configurations on the same bucket cannot share a common event type.`.

Even if we enforced a mechanism such as allowing multiple subscribers only if they define non-overlapping event types, we would be limited by the feature of the SQS queue, which doesn't allow fanning messages out to multiple consumers.

### Proposal

We could enable an alternative mode of notification delivery where a user could select a **SNS topic** (which must exist) instead of a SQS queue, and the source would then create and subscribe one SQS queue to that topic, for each AWSS3Source instance which uses that mode.

Unlike the current SQS-based mode of delivery, external subscribers would now be able to consume bucket notifications as well (fan out).

### Possible API change

**edit**: API change implemented in triggermesh/triggermesh#269

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source

# ...

spec:

  # ...

  destination:  # Optional. Default to 'sqs' with managed queue.

    # Only *one* possible choice per AWSS3Source instance:

    sqs:
      queueARN: arn:aws:sqs:us-west-2:123456789012:triggermeshtest  # Optional. Managed by the source if not provided.

    sns:
      topicARN: arn:aws:sns:us-west-2:123456789012:triggermeshtest
```

### External links

- [SNS - Fanout to Amazon SQS queues](https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html)
