### ISSUE TITLE
Secrets are empty in E2E workflow after merging dependabot's PRs

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#367]
Immediately after merging a PR from Dependabot, E2E tests are executed on the `main` branch with **empty secrets**:

```yaml
  env:
    GOROOT: /opt/hostedtoolcache/go/1.17.5/x64
    KUBECONFIG: /home/runner/.kube/config
    AWS_REGION: 
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
```

For comparison, GitHub Actions show `***` as the value when secret values are successfully populated.

When the (failed) workflow is manually restarted, secrets are effectively populated and the workflow completes.
