### ISSUE TITLE
Status condition `Subscribed` remains "Unknown" when user provides a Pub/Sub subscription ID

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#378]
E2E tests surfaced an issue where the source's status remains "Unknown" when the user provides an explicit `spec.subscriptionID`.

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: GoogleCloudPubSubSource

metadata:
  name: test-k4mb6
  namespace: e2e-googlecloudpubsubsource-4484

spec:
  topic: projects/cebuk-01/topics/e2e-googlecloudpubsubsource-4484
  subscriptionID: e2e-googlecloudpubsubsource-4484
  serviceAccountKey:
    value: ***
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display

status:
  sinkUri: http://event-display.e2e-googlecloudpubsubsource-4484.svc.cluster.local
  subscription: projects/***/subscriptions/e2e-googlecloudpubsubsource-4484
  ceAttributes:
  - source: projects/***/topics/e2e-googlecloudpubsubsource-4484
    type: com.google.cloud.pubsub.message
  conditions:
  - lastTransitionTime: "2021-12-29T10:46:24Z"
    status: "True"
    type: Deployed
  - lastTransitionTime: "2021-12-29T10:46:24Z"
    status: Unknown
    type: Ready
  - lastTransitionTime: "2021-12-29T10:46:23Z"
    status: "True"
    type: SinkProvided
  - lastTransitionTime: "2021-12-29T10:46:23Z"
    status: Unknown  # <------------------------- THIS
    type: Subscribed
```
