### ISSUE TITLE
Finalization blocked when user passes empty inline credentials

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#411]
The following `auth` spec causes the finalization to block forever with the error message below:

```yaml
  auth:
    credentials:
      accessKeyID:
        value: ""
      secretAccessKey:
        value: ""
```

```
LAST SEEN   TYPE      REASON              OBJECT                    MESSAGE
79s         Warning   FailedUnsubscribe   awssnssource/test-w8dds   Error checking the existence of topic: EmptyStaticCreds: static credentials are empty
```

We should probably handle this special case in the `isDenied` condition, since this condition (indirectly) rejects similar error cases such as malformed credentials.
