### ISSUE TITLE
Support both Service Principal (AAD) and SAS Token authentication

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#435]
The event source for Azure IoT Hub only supports Connection String authentication. It should support all three of the following options:

**Service Principal (AAD)**

https://github.com/triggermesh/triggermesh/blob/d741b845131d19e6f1361e11ca4880ce896504a7/config/samples/sources/azureservicebustopicsource.yaml#L29-L36

**Connection String (SAS Token)**

https://github.com/triggermesh/triggermesh/blob/d741b845131d19e6f1361e11ca4880ce896504a7/config/samples/sources/azureservicebusqueuesource.yaml#L29-L32

**Token key/value (SAS Token)**

```yaml
 auth: 
   sasToken: 
     keyName:
       value: ReadOnly
     keyValue:
       value: aHpDel7ZCURMDyixudUeciLODz9SxImqqbEXAMPLEKEY
```
