### ISSUE TITLE
Use a `Tracker` instead of a filtered `EventHandler` to track changes to multi-tenant source adapters

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#47]
We currently track changes to multi-tenant receive adapters by attaching an event handler with a custom filter (`hasAdapterLabelsForType()`) to Deployment/KnService informers.
The filtering occurs on a set of common labels such as

```yaml
app.kubernetes.io/name: zendesksource
app.kubernetes.io/component: adapter
app.kubernetes.io/part-of: triggermesh
app.kubernetes.io/managed-by: triggermesh-controller
```

Code location, for reference:

https://github.com/triggermesh/triggermesh/blob/d208c4b905be5727badff6d28083b5b0ad1a109f/pkg/reconciler/base.go#L170-L173

While this approach works well for us, there has been some effort upstream, especially since Knative v0.26, to use a `Tracker` for that purpose. Here is an example in the upstream event source for GitHub:

https://github.com/knative-sandbox/eventing-github/blob/ee07cd159049aff7e0a2d7eb062e67fee5d45f57/pkg/reconciler/source/controller.go#L78-L85

We should consider evaluating whether using a `Tracker` may indeed simplify the filtering of multi-tenant receive adapters for us.

The conclusion may be that a `Tracker` can only filter by name and not by labels, in which case we may simply close this issue as "won't do".
