### ISSUE TITLE
Cannot set cloudevent extension attributes in transform

### ISSUE THREAD

**Issue by leeish** [triggermesh/triggermesh#591]
When using the `add` operation on the transformer context, adding new attributes doesn't work. It doesn't appear to do anything. Other context attributes will work in the same transformer, but extension attributes seem unable to be added. Tried using various versions including the latest.

```
context:
  - operation: add
    paths:
    - key: profile
      value: something
```

**Comment by tzununbekov** [comment]
@leeish CloudEvent's context extensions can be accessed with `extensions.*` key prefix, eg:

```
context:
  - operation: add
    paths:
    - key: extensions.profile
      value: something
```
