### ISSUE TITLE
Context empty in Python Function

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#594]
Given the following Function object:

```yaml
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: python-function-inference-request
spec:
  runtime: python
  public: true
  entrypoint: validate_inference
  responseIsEvent: true
  ceOverrides:
    extensions:
      type: org.kubeflow.serving.inference
  code: |
    def validate_inference(event, context):
      event['contextz'] = context.ce
      if not context.ce:
        print(event)
        print('Empty context')
        return None
      if context.ce:
        print(context.ce['type'])
      return event
```

The following event causes the Function to see an empty context:

```jsonc
☁️ cloudevents.Event
 Validation: valid
 Context Attributes,
   specversion: 1.0
   type: org.kubeflow.serving.inference.request
   source: http://localhost:9081/
   id: 9ef9363c-3d65-492c-88c2-f08d7abe5efa
   time: 2022-02-24T12:41:03.604103652Z
   datacontenttype: application/json
 Extensions,
   component: predictor
   endpoint: 
   inferenceservicename: model-test-broker
   namespace: kubeflow-user-example-com
   traceparent: 00-63b3f5317127eee1f11f862bdd280608-88c9beea0aa2ece9-00
 Data,
   {
     "instances": [
       [
         2,
         1
       ],
       [
         1,
         2
       ]
     ]
   }
```

Output:

```
2022/02/24 12:19:30 -> 1645705170702767356 200
{'predictions': [1, 1], 'contextz': None}
Empty context
```
