### ISSUE TITLE
Could you please help to example how to use awscloudwatchsource?

### ISSUE THREAD

**Issue by life-learner1** [triggermesh/triggermesh#632]
no idea what I should  do with this fields
https://github.com/triggermesh/triggermesh/blob/main/config/samples/sources/awscloudwatchsource.yaml

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSCloudWatchSource
....
  metricQueries:
  - name: testquery
    metric:
      period: 60
      stat: p90
      unit: Milliseconds
      metric:
        metricName: Duration
        namespace: AWS/Lambda
        dimensions:
        - name: FunctionName
          value: lambdadumper
```

edit: formatting (@antoineco)
