### ISSUE TITLE
Create source for Amazon EventBridge

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#633]
_Originally posted by @life-learner1 in https://github.com/triggermesh/triggermesh/issues/632#issuecomment-1062692116_

---

I want to handle ECR event from EventBridge (CloudWatch Events).

![image](https://user-images.githubusercontent.com/94417934/157406693-94a02e60-8bd3-40d6-a2f2-5045fc36a992.png)

That's the rule:

```json
{
  "detail-type": [
    "ECR Image Action"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "action-type": [
      "PUSH"
    ],
    "result": [
      "SUCCESS"
    ]
  }
}
```

**Comment by sebgoa** [comment]
since @FranBarrera is tackling #615 maybe he can tackle this one as well.

**Comment by antoineco** [comment]
I think the easiest way to source events from EventBridge is to use the same approach as in the S3 source: create a SQS queue, and set this queue as the target of an EventBridge rule.

We have all the code written to achieve this already:
1. [Reconcile a SQS queue](https://github.com/triggermesh/triggermesh/blob/46464eca0ae139fb424fe4b4605e5969603bc281/pkg/sources/reconciler/awss3source/queue.go)
1. [Create an EventBridge rule](https://github.com/triggermesh/test-infra/blob/8aabc32839ff0e5a6ca03e00bfb44e0c30492ecd/test/e2e/targets/awseventbridge/main.go#L147-L150)
1. [Apply an IAM Policy that allows the EventBridge rule to send events to the SQS queue](https://github.com/triggermesh/test-infra/blob/8aabc32839ff0e5a6ca03e00bfb44e0c30492ecd/test/e2e/targets/awseventbridge/main.go#L158-L160)
1. [Set the SQS queue as the target of the EventBridge rule](https://github.com/triggermesh/test-infra/blob/8aabc32839ff0e5a6ca03e00bfb44e0c30492ecd/test/e2e/targets/awseventbridge/main.go#L164-L166)

**Comment by antoineco** [comment]
@life-learner1 just in case you're still interested in this feature, it is being reviewed in #917.

Sample:

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSEventBridgeSource
metadata:
  name: sample
spec:
  arn: arn:aws:events:us-west-2:123456789012:event-bus/triggermeshtest

  eventPattern: |
    {
      "detail-type": [
        "ECR Image Action"
      ],
      "source": [
        "aws.ecr"
      ],
      "detail": {
        "action-type": [
          "PUSH"
        ],
        "result": [
          "SUCCESS"
        ]
      }
    }

  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: awscreds
          key: aws_access_key_id
      secretAccessKey:
        valueFromSecret:
          name: awscreds
          key: aws_secret_access_key

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
```
