### ISSUE TITLE
500 {"errorMessage": "Unable to import module 'source'"}

### ISSUE THREAD

**Issue by life-learner1** [triggermesh/triggermesh#652]
Hi, guys, I took a look at doc,  still not figure it out, this is my Function, BTW, how to install dependency, boto3 and botocore are needed.
```yaml
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: ecr-push-deploy-for-gaia
spec:
  runtime: python
  public: false
  entrypoint: lambda_handler
  code: |
    # -*- coding: utf-8 -*-
    import json 
    from botocore.vendored import requests
    

    def lambda_handler(event, context):
        print(event)
        print(context)

        payload = {
            'repo_name':event["detail"]["repository-name"],
            'image_tag':event["detail"]["image-tag"],
            'event':event["detail"]["action-type"]
        }
```
**and I got error 500, logs:** 
2022/03/14 05:07:36 <- 1647234456601989221 {"Attributes":{"SentTimestamp":"1647234456512"},"Body":"{\"version\":\"0\",\"id\":\"57583141-3bad-8e6f-b000-8d06e76b8863\",\"detail-type\":\"ECR Image Action\",\"source\":\"aws.ecr\",\"account\":\"XXX\",\"time\":\"2022-03-14T05:07:34Z\",\"region\":\"us-west-2\",\"resources\":[],\"detail\":{\"result\":\"SUCCESS\",\"repository-name\":\"hpbp/gaia\",\"image-digest\":\"sha256:00dfb39ecb807e4365e489bd56718eceb3dba837d50e659c897082c55b4417ec\",\"action-type\":\"PUSH\",\"image-tag\":\"PR-1058_a189a7d\"}}","MD5OfBody":"c7817ede2026b9d8e13e3675c96d63e9","MD5OfMessageAttributes":null,"MessageAttributes":null,"MessageId":"625e7509-4b59-49fd-a727-8d7071647033","ReceiptHandle":"AQEBxubPSxHGe4tDMF6aLbfnDsA7CTdc7BkKrR6pPqOVXDH+/xzNV6A3dCWrrfAmI+uf/IsrIaGffHd/gJVe4i0gj+zRl6NguLwdD3c367KiYJapihS3ANWSkRijNtPiWXSXNaVPInR+F78bSrP+uzNvg7B7wBtFGvZpPnORIP79UmIEa1mpnPIvC0kPEhNOtHXAr9HOi+g7pbFc06H4na/w7lTnKcv5BvguZXwLDmtnk1bthUAb1l+3yM5k6bjLxXIn3Op5we7o8tHxrf4+5o994N3SusuX8fTNsRig+o6gilX3zAT7B1zRO/Qv7juASXufKKUJWW2sulx1gaWvDoy/b22jOTzXOMNDkMXMFqL50ETiwBBMW8S3jufHX674ayu2VAjNYuV3Qtz5R/iyvPizpw=="}
2022/03/14 05:07:36 -> 1647234456601989221 500 {"errorMessage": "Unable to import module 'source'"}

**but source.py is just there, I am confused now**
![image](https://user-images.githubusercontent.com/94417934/158111862-16895bff-cca2-4c42-990a-60d709bb9185.png)
