### ISSUE TITLE
Add RPS autoscaling metrics to Knative Service based components.

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/triggermesh#714]
After executing load tests it seems that the safest bet for most common scaling scenarios is using RPS metrics.
Concurrency metrics are more customizable, but it might be harder to provide a generic default configuration.

This is one example of such scaling under a load test:
![cpu](https://user-images.githubusercontent.com/9891289/161959801-628ad352-c7d7-48b1-add6-e97f91cbd255.png)

These are the settings used during load tests we could consider a starting point.

```yaml
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "30"

        autoscaling.knative.dev/scale-down-delay: "5m"

        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "300"
        autoscaling.knative.dev/target-utilization-percentage: "80"
        autoscaling.knative.dev/window: "60s"
```
