### ISSUE TITLE
DeepDerivate semantic comparison ignores EnvVar with emtpy values

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#741]
Consider two Containers with the following env vars:

```yaml
# desired
env:
- name: FOO
  value: ''
- name: BAR
  value: something
```

```yaml
# current
env:
- name: FOO
  value: something
- name: BAR
  value: something
```

Because the DeepDerivative semantic comparison compares fields _one by one_ instead of considering the `EnvVar` as a whole, those two containers are wrongfully considered equal.

Here is a test case that reproduces the problem:

```patch
diff --git a/pkg/reconciler/semantic/semantic_test.go b/pkg/reconciler/semantic/semantic_test.go
index a57deae0..0e66eba2 100644
--- a/pkg/reconciler/semantic/semantic_test.go
+++ b/pkg/reconciler/semantic/semantic_test.go
@@ -96,6 +101,14 @@ func TestDeploymentEqual(t *testing.T) {
                        },
                        false,
                },
+               "not equal when EnvVar desired value is empty": {
+                       func() *appsv1.Deployment {
+                               desired := current.DeepCopy()
+                               desired.Spec.Template.Spec.Containers[0].Env[0].Value = ""
+                               return desired
+                       },
+                       false,
+               },
        }
```
