### ISSUE TITLE
`config/500-controller.yaml` Container could be running with outdated image

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#866]
```
   - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://github.com/triggermesh/triggermesh/cmd/triggermesh-controller

        resources:
```

## Details
Introduced through: [DocId: 0] › spec › template › spec › containers[controller] › imagePullPolicy

### This issue is...
The image policy does not prevent image reuse

### The impact of this is...
The container may run with outdated or unauthorized image

### You can resolve it by...
Set imagePullPolicy attribute to Always
