### ISSUE TITLE
`config/500-controller.yaml` Container is running with writable root filesystem

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#867]
```
 securityContext:
          allowPrivilegeEscalation: false

        ports:
        - name: metrics
```

Introduced through: [DocId: 0] › input › spec › template › spec › containers[controller] › securityContext › readOnlyRootFilesystem

This issue is...
readOnlyRootFilesystem attribute is not set to true

The impact of this is...
Compromised process could abuse writable root filesystem to elevate privileges

You can resolve it by...
Set securityContext.readOnlyRootFilesystem to true
