### ISSUE TITLE
`config/500-controller.yaml` - Container is running without cpu limit

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#868]
```
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
```

Introduced through: [DocId: 0] › input › spec › template › spec › containers[controller] › resources › limits › cpu
Show less details 
This issue is...
CPU limit is not defined

The impact of this is...
Containers without limits can exceed the capacity of the node, and affect availability/performance of the host and other containers.

You can resolve it by...
Add resources.limits.cpu field with required CPU limit value
