### ISSUE TITLE
`config/500-controller.yaml` Container is running without liveness probe

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#869]
```
      - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://github.com/triggermesh/triggermesh/cmd/triggermesh-controller

        resources:
```
Introduced through: [DocId: 0] › spec › template › spec › containers[controller] › livenessProbe

This issue is...
Liveness probe is not defined

The impact of this is...
Kubernetes will not be able to detect if application is able to service requests, and will not restart unhealthy pods

You can resolve it by...
Add livenessProbe attribute
