### ISSUE TITLE
`config/500-controller.yaml` - Container is running without memory limit

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#870]
```
       resources:
          requests:
            cpu: 50m
            memory: 20Mi
```

Introduced through: [DocId: 0] › input › spec › template › spec › containers[controller] › resources › limits › memory

This issue is...
Memory limit is not defined

The impact of this is...
Containers without memory limits are more likely to be terminated when the node runs out of memory

You can resolve it by...
Set resources.limits.memory value
