### ISSUE TITLE
adapterOverrides is not overriding resource limts/requests for awss3source

### ISSUE THREAD

**Issue by jeesmon** [triggermesh/triggermesh#909]
Following documentation for `AWSS3Source` from knative here: https://knative.dev/docs/eventing/sources/#third-party-sources, example deployment https://github.com/triggermesh/triggermesh/blob/main/config/samples/sources/awss3source.yaml goes into `CrashLoopBackOff` due to small resource limit. But overriding resource limits/requests is not updating the `awss3source-sample` deployment.

I'm using triggermesh v1.17.0

```yaml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: sample
spec:
  arn: arn:aws:s3:us-east-1:xxx:yyy

  eventTypes:
  - s3:ObjectCreated:*
  - s3:ObjectRemoved:*

  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: awscreds
          key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        valueFromSecret:
          name: awscreds
          key: AWS_SECRET_ACCESS_KEY

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

  adapterOverrides:
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: 90m
        memory: 30Mi
```

```console
$ kubectl get deploy awss3source-sample -o yaml|grep -A6 resources:
        resources:
          limits:
            cpu: "1"
            memory: 45Mi
          requests:
            cpu: 90m
            memory: 30Mi
```

```console         
$ kubectl get awss3source
NAME     READY   REASON               QUEUE                                                        SINK                                               AGE
sample   False   AdapterUnavailable   arn:aws:sqs:us-east-1:xxx:zzzz   http://event-display.s3-events.svc.cluster.local   51m
```

Any help to fix the resource limits is highly appreciated.

edit: formatting (@antoineco)
